CREATE TABLE eagle_monitor.eagle_transactions_flat (
    transaction_id UNIQUEIDENTIFIER NOT NULL,
    transactiondate DATETIME NOT NULL,
    sender_name NVARCHAR(100),
    sender_address NVARCHAR(255),
    sender_account_number NVARCHAR(50),
    sender_bank_name NVARCHAR(100),
    sender_swift_code NVARCHAR(50),
    receiver_name NVARCHAR(100),
    receiver_address NVARCHAR(255),
    receiver_account_number NVARCHAR(50),
    receiver_bank_name NVARCHAR(100),
    receiver_swift_code NVARCHAR(50),
    amount_usd DECIMAL(18, 2),
    sender_country NVARCHAR(10),
    receiver_country NVARCHAR(10),
	transaction_type NVARCHAR(50),
	"status" NVARCHAR(50),
	fee_usd DECIMAL(18, 2),
	reference NVARCHAR(100),
	processing_time DATETIME NOT NULL,
	ip_address NVARCHAR(50),
	device_id NVARCHAR(50),
	user_agent  NVARCHAR(MAX),
	channel NVARCHAR(50),
);

