SELECT TOP (1000) [transaction_id]
      ,[transactiondate]
      ,[sender_name]
      ,[sender_address]
      ,[sender_account_number]
      ,[sender_bank_name]
      ,[sender_swift_code]
      ,[receiver_name]
      ,[receiver_address]
      ,[receiver_account_number]
      ,[receiver_bank_name]
      ,[receiver_swift_code]
      ,[amount_usd]
      ,[sender_country]
      ,[receiver_country]
      ,[transaction_type]
      ,[status]
      ,[fee_usd]
      ,[reference]
      ,[processing_time]
      ,[ip_address]
      ,[device_id]
      ,[user_agent]
      ,[channel]
  FROM [eagle_monitor].[eagle_transactions_flat]
